#!/usr/bin/env python3
"""
    This utility creates an Alpine Linux overlay tarball in an ISO to help with automated headless
    installs.

    I wouldn't have been able to do this without the help of Copilot, however the code has been 
    significantly improved over the original suggestions with the aim being the absolute minimal
    script and answerfile to get the job done.  It's expected that either Ansible or some other 
    config management tools will be used post-install to do the bulk of the system configuration.
    All this tries to deliver is passwordless ssh access to a running system.

    I have tested this only on Proxmox but it should work on any virtualization platform that supports
    multiple CD-ROM drives.  It's possible to put the overlay on a floppy image or USB stick but
    these options make things more complicated for Proxmox because it has convenient special treatment
    for ISO images (the ISO store).   I haven't tested this but I believe Alpine will mount any 
    removable media and extract the overlay tarball so long as it's named correctly.  Try it on a 
    second USB stick for headless hardware installs from boot.

    Requires:
    - python3 (base install will be good enough, no VENVs or additional packages needed)
    - mkisofs ('brew install cdrtools' on Macos, or use your distro's package manager for Linux)
    - Pub/priv keypair in ~/.ssh 

    Usage example:
    ./build_alpine_overlay.py --hostname myalpine --out myalpine_apkovl.iso

"""

import os
import argparse
import sys
import tarfile
import io
from pathlib import Path
from subprocess import run, CalledProcessError
import shutil
from io import StringIO


# OpenRC service template for unattended setup-alpine
# Placed in the overlay tarball at /etc/init.d/autosetup
AUTOS_SETUP_TEMPLATE = '''#!/sbin/openrc-run
name="Autosetup Alpine"
description="Run unattended setup-alpine on first boot"

depend() {
    need sysfs devfs mdev localmount modloop
    after modules bootmisc
}

start() {
    if [ -f /root/.autosetup.done ]; then
        einfo "Autosetup already done"
        return 0
    fi
    export ERASE_DISKS="%(disk)s"
    einfo "Running setup-alpine"
    setup-alpine -e -f /root/answers || return 1
    touch /root/.autosetup.done
    einfo "Autosetup complete"
    poweroff
}
'''


# setup-alpine answerfile template
# Placed in the overlay tarball at /root/answers
ANSWERS_TEMPLATE = '''# setup-alpine answerfile (autogenerated)
KEYMAPOPTS="%(keymap)s"
HOSTNAMEOPTS=%(hostname)s
DEVDOPTS=%(devdopts)s
INTERFACESOPTS="%(interfaces)s\n"
DNSOPTS=none
TIMEZONEOPTS="%(timezone)s"
PROXYOPTS=none
APKREPOSOPTS="-1 -c"
NTPOPTS=none
SSHDOPTS=openssh
# Skip creating a non-root user during unattended install
USEROPTS=none
# Disk configuration: sys mode on stated disk, no swap
DISKOPTS="-m sys -s 0 %(disk)s"
'''


# default interfaces content used by INTERFACESOPTS
INTERFACES_DHCP = '''auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
'''


HOME_DIR = Path.home()
SSH_DIR = HOME_DIR / ".ssh"

# Location in ~/.ssh to look for public keys to include in root's authorized_keys
# It's almost certainly safe to leave this list as-is but if you only want specific keys
# to be included, modify this list accordingly, and if it misses your key name, add it.
PUBLIC_KEYS = [
        SSH_DIR / "id_ed25519.pub",
        SSH_DIR / "id_rsa.pub",
        SSH_DIR / "id_ecdsa.pub",
        SSH_DIR / "id_dsa.pub",
        # security key variants if present
        SSH_DIR / "id_ed25519_sk.pub",
        SSH_DIR / "id_ecdsa_sk.pub",
    ]


class OverlayTar:
    def __init__(self, out_path: str):
        self.out_path = out_path
        self.added: set[str] = set()
        if os.path.exists(self.out_path):
            os.unlink(self.out_path)
        self.tf = tarfile.open(self.out_path, "w:gz")

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        self.tf.close()

    def file(self, path: str, data: bytes | str, mode: int = 0o644):
        bin_data = data.encode()
        ti = tarfile.TarInfo(path)
        ti.size = len(bin_data)
        ti.mode = mode
        self.tf.addfile(ti, io.BytesIO(bin_data))

    def symlink(self, path: str, target: str):
        ti = tarfile.TarInfo(path)
        ti.type = tarfile.SYMTYPE
        ti.linkname = target
        ti.mode = 0o777
        self.tf.addfile(ti)

    def dir(self, path: str, mode: int = 0o755):
        ti = tarfile.TarInfo(path)
        ti.type = tarfile.DIRTYPE
        ti.mode = mode
        self.tf.addfile(ti)


def gather_authorized_keys() -> str:
    out = StringIO()
    for path in PUBLIC_KEYS:
        if path.exists():
            out.write(path.read_text().strip() + "\n")
    result = out.getvalue()
    if not result:
        raise RuntimeError("No SSH public keys found in ~/.ssh; authorized_keys is required")
    return result


def build_answers(args) -> str:
    # Populate defaults for template-driven fields if not provided
    if getattr(args, "interfaces", None) is None:
        args.interfaces = INTERFACES_DHCP
    if getattr(args, "devdopts", None) is None:
        args.devdopts = "mdev"

    return ANSWERS_TEMPLATE % vars(args)


def create_overlay_tar(out_path: str, args):
    autosetup_content = AUTOS_SETUP_TEMPLATE % vars(args)
    answers_txt = build_answers(args)

    with OverlayTar(out_path) as ovl:
        # Minimal OpenRC autosetup service to run installer once
        ovl.file("etc/init.d/autosetup", autosetup_content, 0o755)
        # Enable autosetup at default runlevel (absolute target for busybox tar)
        ovl.dir("etc/runlevels/default/", 0o755)
        ovl.symlink("etc/runlevels/default/autosetup", "/etc/init.d/autosetup")
        # Ensure modloop is started during sysinit so /lib/modules is populated
        ovl.dir("etc/runlevels/sysinit/", 0o755)
        ovl.symlink("etc/runlevels/sysinit/modloop", "/etc/init.d/modloop")
        ovl.file("root/answers", answers_txt + "\n", 0o644)
        # Include SSH authorized_keys with secure perms (required)
        keys = gather_authorized_keys()
        ovl.dir("root/.ssh/", 0o700)
        ovl.file("root/.ssh/authorized_keys", keys, 0o600)


def build_iso(tarball_name: str, dest_iso: Path):
    mk = shutil.which("mkisofs")
    if not mk:
        raise ValueError("mkisofs not found")
    
    print(f"Creating ISO {dest_iso} with {tarball_name} at root...")
    try:
        run(["mkisofs", "-J", "-R", "-V", "APKOVL", "-o", str(dest_iso), f"{tarball_name}"], check=True)
    except CalledProcessError as e:
        print(f"mkisofs failed: {e}", file=sys.stderr)
        sys.exit(e.returncode)
    print(f"Created {dest_iso}")


def main():
    parser = argparse.ArgumentParser(description="Build headless Alpine overlay ISO (apkovl inside)")
    parser.add_argument("--hostname", required=True, help="Target hostname")
    parser.add_argument("--out", default="apkovl.iso", help="Output ISO path suffix")
    parser.add_argument("--disk", default="/dev/sda", help="Install disk device (e.g., /dev/sda or /dev/vda)")
    parser.add_argument("--timezone", default="GMT", help="Timezone (under /usr/share/zoneinfo)")
    parser.add_argument("--keymap", default="us us", help="Keymap layout and variant (e.g., 'us us' or 'none')")
    parser.add_argument("--devdopts", default=None, help="Device manager option (e.g., 'mdev' or 'none'); default 'mdev' if omitted")
    parser.add_argument("--interfaces", default=None, help="Full /etc/network/interfaces content; default DHCP template if omitted")
    # Hardcoded inner filename expected by headless Alpine discovery
    tarball_name = "alpine.apkovl.tar.gz"

    args = parser.parse_args()
    dest_iso = Path(args.hostname + '_' + args.out)

    create_overlay_tar(tarball_name, args)
    build_iso(tarball_name, dest_iso)


if __name__ == "__main__":
    main()
